# Book settings
title: Data Science 1
author: Tobin A. Driscoll
logo: logo.png
copyright: "2022"

exclude_patterns: 
  - etc/*.ipynb

parse:
  myst_enable_extensions:
  - amsmath
  - colon_fence
  - deflist
  - dollarmath
  - html_image
  - linkify
#  - replacements

kernelspec:
  name: python3
  display_name: Python 3
  language: python

latex:
  latex_documents:
    targetname: datasci1.tex
  latex_engine: xelatex

execute:
  execute_notebooks: cache
  timeout: 120
  allow_errors: true
  run_in_temp: false

html:
  favicon: favicon.ico
  extra_footer: "<img alt='UD logo' src='_static/UDlogo-small.png'>"
  # google_analytics_id: UA-172898555-1

sphinx:
  config:
    numfig_secnum_depth: 2
    # pygments_style: fnc
    mathjax3_config:
      tex:
        macros:
          "float": ["\\mathbb{F}"]
          "real": ["\\mathbb{R}"]
          "complex": ["\\mathbb{C}"]
          "nat": ["\\mathbb{N}"]
          "integer": ["\\mathbb{Z}"]
          "bfa" : "\\mathbf{a}"
          "bfe" : "\\mathbf{e}"
          "bfx" : "\\mathbf{x}"
          "bfX" : "\\mathbf{X}"
          "bfu" : "\\mathbf{u}"
          "bfv" : "\\mathbf{v}"
          "bfw" : "\\mathbf{w}"
          "bfy" : "\\mathbf{y}"
          "bfz" : "\\mathbf{z}"
          "bfzero" : "\\boldsymbol{0}"
          "bfmu" : "\\boldsymbol{\\mu}"
          "TP" : "\\text{TP}"
          "TN" : "\\text{TN}"
          "FP" : "\\text{FP}"
          "FN" : "\\text{FN}"
          "rmn" : ["\\mathbb{R}^{#1 \\times #2}",2]
          "dd" : ["\\frac{d #1}{d #2}",2]
          "pp" : ["\\frac{\\partial #1}{\\partial #2}",2]
          "norm" : ["\\lVert #1 \\rVert",1]
          "twonorm" : ["\\norm{#1}_2",1]
          "onenorm" : ["\\norm{#1}_1",1]
          "infnorm" : ["\\norm{#1}_\\infty",1]
          "innerprod" : ["\\langle #1,#2 \\rangle",2]
          "pr" : ["^{(#1)}",1]
          "diag": ["\\operatorname{diag}"]
          "sign": ["\\operatorname{sign}"]
          "ee": ["\\times 10^"]
          "floor": ["\\lfloor#1\\rfloor",1]
          "argmin": ["\\operatorname{argmin}"]
          "Cov": ["\\operatorname{Cov}"]
          "logit": ["\\operatorname{logit}"]
    
    latex_additional_files: etc/preamble.tex
    latex_elements:
      preamble: >
        \usepackage{mathtools}
        \usepackage{fontspec}
        \usepackage{unicode-math}
        \setmainfont[Ligatures=TeX]{TeX Gyre Schola}
        \setmathfont{TeX Gyre Schola Math}
        \include{preamble}
      passoptionstopackages: \PassOptionsToPackage{svgnames}{xcolor}
      sphinxsetup: verbatimwithframe=false,VerbatimColor={RGB}{255,252,245}

  extra_extensions:
  - sphinx_proof
  # - sphinx_jupyterbook_latex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/UD-Math-Data-Science-1/notes # Online location of your book
  # book_path                 : notes  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook-interface: "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe: true