# Book settings
title: Fundamentals of Numerical Computation
author: Tobin A. Driscoll and Richard J. Braun
logo: logo.svg

exclude_patterns: 
  - solutions/*
  - etc/*
  - localapprox/B-splines.md
  - tmp/*
  - tex/*

parse:
  myst_enable_extensions:
  - amsmath
  - colon_fence
  - deflist
  - dollarmath
  - html_image
  - linkify
#  - replacements

latex:
  latex_documents:
    targetname: fnc-julia.tex
  latex_engine: xelatex

kernelspec:
  name: julia-1.6
  display_name: Julia 1.6.1
  language: julia
  
execute:
  execute_notebooks: cache
  timeout: 120
  allow_errors: true
  run_in_temp: false

html:
  favicon: etc/favicon.png
  # google_analytics_id: UA-172898555-1

sphinx:
  config:
    numfig_secnum_depth: 2
    pygments_style: fnc
    mathjax_config:
      TeX:
        Macros:
          "float": ["\\mathbb{F}"]
          "real": ["\\mathbb{R}"]
          "complex": ["\\mathbb{C}"]
          "nat": ["\\mathbb{N}"]
          "integer": ["\\mathbb{Z}"]
          "rmn{([^}]*)}{([^}]*)}" : ["\\mathbb{R}^{#1 \\times #2}",2]
          "dd{([^}]*)}{([^}]*)}" : ["\\frac{d #1}{d #2}",2]
          "ddd{([^}]*)}{([^}]*)}" : ["\\frac{d^2 #1}{d #2^2}",2]
          "pp{([^}]*)}{([^}]*)}" : ["\\frac{\\partial #1}{\\partial #2}",2]
          "ppp{([^}]*)}{([^}]*)}" : ["\\frac{\\partial^2 #1}{\\partial #2^2}",2]
          "ppdd{([^}]*)}{([^}]*)}{([^}]*)}" : ["\\frac{\\partial^2 #1}{\\partial #2 \\partial #3}",3]
          "norm{([^}]*)}" : ["\\| #1 \\|",1]
          "twonorm{([^}]*)}" : ["\\| #1 \\|_2",1]
          "onenorm{([^}]*)}" : ["\\| #1 \\|_1",1]
          "infnorm{([^}]*)}" : ["\\| #1 \\|_\\infty",1]
          "anynorm{([^}]*)}{([^}]*)}" : ["\\| #1 \\|_#2",2]
          "infnorm{([^}]*)}" : ["\\| #1 \\|_\\infty",1]
          "innerprod{([^}]*)}{([^}]*)}" : ["\\langle #1,#2 \\rangle",2]
          "pr{([^}]*)}" : ["^{(#1)}",1]
          "kron{([^}]*)}{([^}]*)}" : ["#1 \\otimes #2",2]
          "eye{([^}]*)}" : ["\\mathbf{e}_#1",1]
          "meye" : ["\\mathbf{I}"]
          "Qhat" : ["\\hat{\\mathbf{Q}}"]
          "Rhat" : ["\\hat{\\mathbf{R}}"]
          "bfalpha": ["\\mathbf{alpha}"]
          "bfdelta": ["\\mathbf{delta}"]
          "bfzero": ["\\boldsymbol{0}"]
          "macheps": ["\\epsilon_\\text{mach}"]
          "fl": ["\\operatorname{fl}"]
          "diag": ["\\operatorname{diag}"]
          "ign": ["\\operatorname{sign}"]
          "Re": ["\\operatorname{Re}"]
          "Im": ["\\operatorname{Im}"]
          "ee": ["\\times 10^"]
          "lnorm": ["\\|"]
          "rnorm": ["\\|"]
          "floor": ["\\lfloor#1\\rfloor",1]
          "cI": ["\\mathcal{I}"]
          "mtx": ["\\operatorname{mtx}"]
          "myvec": ["\\operatorname{vec}"]
          "argmin": ["\\operatorname{argmin}"]
      HTML-CSS:
        availableFonts: []
        preferredFont: null
        #webFont: Gyre-Termes
        #webFont: Asana-Math
        webfont: Latin-Modern
    proof_theorem_types:
      "algorithm": "Algorithm"
      "conjecture": "Conjecture"
      "corollary": "Corollary"
      "definition": "Definition"
      "demo": "Demo"
      "example": "Example"
      "formula": "Formula"
      "function": "Function"
      "lemma": "Lemma"
      "observation": "Observation"
      "proof": "Proof"
      "property": "Property"
      "myrule": "Rule"
      "theorem": "Theorem"
    proof_html_nonumbers:
    - "proof"
    - "myrule"
    proof_html_title_template_visit: >
      <div class="proof-title">
      <span class="proof-type">{{ thmtype }} {% if number %}{{number}}{% endif %}</span>
      {% if title %}
      <span class="proof-title-name">: &nbsp;
      {%- endif -%}
    proof_html_title_template_depart: >
      {%- if title -%}
      </span>
      {% endif %}
      </div>
 
    latex_additional_files: tex/preamble.tex
    latex_elements:
      preamble: >
        \include{preamble}
        \usepackage{marvosym}
      passoptionstopackages: \PassOptionsToPackage{svgnames}{xcolor}
      sphinxsetup: verbatimwithframe=false,VerbatimColor={RGB}{255,252,245}

  extra_extensions:
  - sphinxcontrib.proof
  - sphinx_jupyterbook_latex

bibtex_bibfiles:
   - FNC.bib

# Information about where the book exists on the web
repository:
  url                       : https://github.com/tobydriscoll/tobydriscoll.github.io/  # Online location of your book
  book_path                 : unlinked/fnc  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

# launch_buttons:
#   binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
#   thebelab: true